### ISSUE TITLE
Make Web Server to Host Website 

### ISSUE THREAD

**Issue by OpticFractureSupport** [OpticFracture/DownFall#3]
Create web server on AWS to host website. Assign Weebly DNS to forward to server IP address.

Assigned to Sam

**Comment by BerndtSam** [comment]
http://OpticFracture.com
AWS Login: Support@OpticFracture.com

**Comment by BerndtSam** [comment]
@Carson please update billing info on AWS

**Comment by BerndtSam** [comment]
Issue moved to [OpticFracture/Website #2](https://github.com/OpticFracture/Website/issues/2) via [**ZenHub**](https://www.zenhub.com/)
